INSERT INTO app_user (name, email, password) VALUES
                                                 ('Aarav Sharma', 'aarav@gmail.com', 'Password'),
                                                 ('Vivaan Khanna', 'vivaan.khanna@example.com', '$2a$10$examplePasswordHash2'),
                                                 ('Aditya Verma', 'aditya.verma@example.com', '$2a$10$examplePasswordHash3'),
                                                 ('Vihaan Kapoor', 'vihaan.kapoor@example.com', '$2a$10$examplePasswordHash4'),
                                                 ('Arjun Patel', 'arjun.patel@example.com', '$2a$10$examplePasswordHash5'),
                                                 ('Sai Reddy', 'sai.reddy@example.com', '$2a$10$examplePasswordHash6'),
                                                 ('Ananya Nair', 'ananya.nair@example.com', '$2a$10$examplePasswordHash7'),
                                                 ('Ishaan Thakur', 'ishaan.thakur@example.com', '$2a$10$examplePasswordHash8'),
                                                 ('Aryan Rao', 'aryan.rao@example.com', '$2a$10$examplePasswordHash9'),
                                                 ('Diya Singh', 'diya.singh@example.com', '$2a$10$examplePasswordHash10'),
                                                 ('Kabir Joshi', 'kabir.joshi@example.com', '$2a$10$examplePasswordHash11'),
                                                 ('Krishna Iyer', 'krishna.iyer@example.com', '$2a$10$examplePasswordHash12'),
                                                 ('Reyansh Pandey', 'reyansh.pandey@example.com', '$2a$10$examplePasswordHash13'),
                                                 ('Ayaan Mehta', 'ayaan.mehta@example.com', '$2a$10$examplePasswordHash14'),
                                                 ('Anaya Mishra', 'anaya.mishra@example.com', '$2a$10$examplePasswordHash15'),
                                                 ('Navya Kulkarni', 'navya.kulkarni@example.com', '$2a$10$examplePasswordHash16'),
                                                 ('Naira Desai', 'naira.desai@example.com', '$2a$10$examplePasswordHash17'),
                                                 ('Dhruv Saxena', 'dhruv.saxena@example.com', '$2a$10$examplePasswordHash18'),
                                                 ('Sara Bajaj', 'sara.bajaj@example.com', '$2a$10$examplePasswordHash19'),
                                                 ('Arnav Malhotra', 'arnav.malhotra@example.com', '$2a$10$examplePasswordHash20'),
                                                 ('Rahul Kumar', 'rahul.kumar@example.com', '$2a$10$examplePasswordHash21'),
                                                 ('Rohit Gupta', 'rohit.gupta@example.com', '$2a$10$examplePasswordHash22'),
                                                 ('Pooja Sharma', 'pooja.sharma@example.com', '$2a$10$examplePasswordHash23'),
                                                 ('Karan Singh', 'karan.singh@example.com', '$2a$10$examplePasswordHash24'),
                                                 ('Sonia Mehta', 'sonia.mehta@example.com', '$2a$10$examplePasswordHash25'),
                                                 ('Anil Kapoor', 'anil.kapoor@example.com', '$2a$10$examplePasswordHash26'),
                                                 ('Deepak Verma', 'deepak.verma@example.com', '$2a$10$examplePasswordHash27'),
                                                 ('Sneha Jain', 'sneha.jain@example.com', '$2a$10$examplePasswordHash28'),
                                                 ('Ajay Mishra', 'ajay.mishra@example.com', '$2a$10$examplePasswordHash29'),
                                                 ('Nisha Reddy', 'nisha.reddy@example.com', '$2a$10$examplePasswordHash30'),
                                                 ('Vikas Joshi', 'vikas.joshi@example.com', '$2a$10$examplePasswordHash31'),
                                                 ('Meena Desai', 'meena.desai@example.com', '$2a$10$examplePasswordHash32'),
                                                 ('Rajesh Iyer', 'rajesh.iyer@example.com', '$2a$10$examplePasswordHash33'),
                                                 ('Suresh Nair', 'suresh.nair@example.com', '$2a$10$examplePasswordHash34'),
                                                 ('Kavita Singh', 'kavita.singh@example.com', '$2a$10$examplePasswordHash35'),
                                                 ('Ankur Saxena', 'ankur.saxena@example.com', '$2a$10$examplePasswordHash36'),
                                                 ('Geeta Bajaj', 'geeta.bajaj@example.com', '$2a$10$examplePasswordHash37'),
                                                 ('Ramesh Malhotra', 'ramesh.malhotra@example.com', '$2a$10$examplePasswordHash38'),
                                                 ('Seema Rao', 'seema.rao@example.com', '$2a$10$examplePasswordHash39'),
                                                 ('Tarun Sharma', 'tarun.sharma@example.com', '$2a$10$examplePasswordHash40');

INSERT INTO user_roles (user_id, roles) VALUES
                                            (1, 'RIDER'),
                                            (2, 'RIDER'), (2, 'DRIVER'),
                                            (3, 'RIDER'),(3, 'DRIVER'),
                                            (4, 'RIDER'),(4, 'DRIVER'),
                                            (5, 'RIDER'),(5, 'DRIVER'),
                                            (6, 'RIDER'),(6, 'DRIVER'),
                                            (7, 'RIDER'),
                                            (7, 'DRIVER'),
                                            (8, 'RIDER'),
                                            (8, 'DRIVER'),
                                            (9, 'RIDER'),
                                            (9, 'DRIVER'),
                                            (10, 'RIDER'),
                                            (10, 'DRIVER'),
                                            (11, 'RIDER'),
                                            (11, 'DRIVER'),
                                            (12, 'RIDER'),
                                            (12, 'DRIVER'),
                                            (13, 'RIDER'),
                                            (13, 'DRIVER'),
                                            (14, 'RIDER'),
                                            (14, 'DRIVER'),
                                            (15, 'RIDER'),
                                            (15, 'DRIVER'),
                                            (16, 'RIDER'),
                                            (16, 'DRIVER'),
                                            (17, 'RIDER'),
                                            (17, 'DRIVER'),
                                            (18, 'RIDER'),
                                            (18, 'DRIVER'),
                                            (19, 'RIDER'),
                                            (19, 'DRIVER'),
                                            (20, 'RIDER'),
                                            (20, 'DRIVER'),
                                            (21, 'RIDER'),
                                            (21, 'DRIVER'),
                                            (22, 'RIDER'),
                                            (22, 'DRIVER'),
                                            (23, 'RIDER'),
                                            (23, 'DRIVER'),
                                            (24, 'RIDER'),
                                            (24, 'DRIVER'),
                                            (25, 'RIDER'),
                                            (25, 'DRIVER'),
                                            (26, 'RIDER'),
                                            (26, 'DRIVER'),
                                            (27, 'RIDER'),
                                            (27, 'DRIVER'),
                                            (28, 'RIDER'),
                                            (28, 'DRIVER'),
                                            (29, 'RIDER'),
                                            (29, 'DRIVER'),
                                            (30, 'RIDER'),
                                            (30, 'DRIVER'),
                                            (31, 'RIDER'),
                                            (31, 'DRIVER'),
                                            (32, 'RIDER'),
                                            (32, 'DRIVER'),
                                            (33, 'RIDER'),
                                            (33, 'DRIVER'),
                                            (34, 'RIDER'),
                                            (34, 'DRIVER'),
                                            (35, 'RIDER'),
                                            (35, 'DRIVER'),
                                            (36, 'RIDER'),
                                            (36, 'DRIVER'),
                                            (37, 'RIDER'),
                                            (37, 'DRIVER'),
                                            (38, 'RIDER'),
                                            (38, 'DRIVER'),
                                            (39, 'RIDER'),
                                            (39, 'DRIVER'),
                                            (40, 'RIDER'),
                                            (40, 'DRIVER');

INSERT INTO rider (id, user_id, rating) VALUES
    (1, 1, 4.9);



INSERT INTO driver (id, user_id, rating, available, current_location) VALUES
                                                                          (2, 2, 4.8, true, ST_GeomFromText('POINT(79.600943 17.980695)', 4326)),
                                                                          (3, 3, 4.0, true, ST_GeomFromText('POINT(79.605000 17.983000)', 4326)),
                                                                          (4, 4, 4.5, true, ST_GeomFromText('POINT(79.615000 17.981000)', 4326)),
                                                                          (5, 5, 4.0, true, ST_GeomFromText('POINT(79.593000 17.986000)', 4326)),
                                                                          (6, 6, 4.3, true, ST_GeomFromText('POINT(79.602000 17.985000)', 4326)),
                                                                          (7, 7, 4.4, true, ST_GeomFromText('POINT(79.590000 17.982500)', 4326)),
                                                                          (8, 8, 4.4, true, ST_GeomFromText('POINT(79.595000 17.983500)', 4326)),
                                                                          (9, 9, 4.3, true, ST_GeomFromText('POINT(79.600000 17.979500)', 4326)),
                                                                          (10, 10, 4.7, true, ST_GeomFromText('POINT(79.606000 17.980000)', 4326)),
                                                                          (11, 11, 4.1, true, ST_GeomFromText('POINT(79.593500 17.983500)', 4326)),
                                                                          (12, 12, 4.2, true, ST_GeomFromText('POINT(79.600500 17.982500)', 4326)),
                                                                          (13, 13, 4.4, true, ST_GeomFromText('POINT(79.610000 17.979000)', 4326)),
                                                                          (14, 14, 4.2, true, ST_GeomFromText('POINT(79.605500 17.981500)', 4326)),
                                                                          (15, 15, 4.0, true, ST_GeomFromText('POINT(79.589500 17.982000)', 4326)),
                                                                          (16, 16, 4.3, true, ST_GeomFromText('POINT(79.592500 17.979000)', 4326)),
                                                                          (17, 17, 4.6, true, ST_GeomFromText('POINT(79.588000 17.980500)', 4326)),
                                                                          (18, 18, 4.5, true, ST_GeomFromText('POINT(79.600000 17.981000)', 4326)),
                                                                          (19, 19, 4.1, true, ST_GeomFromText('POINT(79.595500 17.980000)', 4326)),
                                                                          (20, 20, 4.3, true, ST_GeomFromText('POINT(79.593000 17.985500)', 4326)),
                                                                          (21, 21, 4.9, true, ST_GeomFromText('POINT(79.605500 17.980000)', 4326)),
                                                                          (22, 22, 4.6, true, ST_GeomFromText('POINT(79.589000 17.981500)', 4326)),
                                                                          (23, 23, 4.8, true, ST_GeomFromText('POINT(79.607500 17.981000)', 4326)),
                                                                          (24, 24, 4.6, true, ST_GeomFromText('POINT(79.596000 17.983000)', 4326)),
                                                                          (25, 25, 4.7, true, ST_GeomFromText('POINT(79.602500 17.984000)', 4326)),
                                                                          (26, 26, 4.5, true, ST_GeomFromText('POINT(79.592000 17.981500)', 4326)),
                                                                          (27, 27, 4.2, true, ST_GeomFromText('POINT(79.594000 17.983500)', 4326)),
                                                                          (28, 28, 4.2, true, ST_GeomFromText('POINT(79.598000 17.979500)', 4326)),
                                                                          (29, 29, 4.1, true, ST_GeomFromText('POINT(79.601000 17.981500)', 4326)),
                                                                          (30, 30, 4.8, true, ST_GeomFromText('POINT(79.595500 17.982500)', 4326)),
                                                                          (31, 31, 4.5, true, ST_GeomFromText('POINT(79.608000 17.983500)', 4326)),
                                                                          (32, 32, 4.0, true, ST_GeomFromText('POINT(79.590500 17.982000)', 4326)),
                                                                          (33, 33, 4.1, true, ST_GeomFromText('POINT(79.602500 17.984500)', 4326)),
                                                                          (34, 34, 4.2, true, ST_GeomFromText('POINT(79.609500 17.980500)', 4326)),
                                                                          (35, 35, 4.0, true, ST_GeomFromText('POINT(79.589000 17.981000)', 4326)),
                                                                          (36, 36, 4.9, true, ST_GeomFromText('POINT(79.596500 17.982000)', 4326)),
                                                                          (37, 37, 4.9, true, ST_GeomFromText('POINT(79.599500 17.983000)', 4326)),
                                                                          (38, 38, 4.4, true, ST_GeomFromText('POINT(79.595000 17.980500)', 4326)),
                                                                          (39, 39, 4.0, true, ST_GeomFromText('POINT(79.597500 17.980000)', 4326));
